export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGING_SUCCESS = "USER_LOGGING_SUCCESS";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_INVALID_CREDENTIALS = "USER_INVALID_CREDENTIALS";
export const FORCE_LOGOUT_USER = "FORCE_LOGOUT_USER";

export const REQUEST_PROFILE = "REQUEST_PROFILE";
export const REQUEST_PROFILE_SUCCESS = "REQUEST_PROFILE_SUCCESS";
export const REQUEST_PROFILE_FAILED = "REQUEST_PROFILE_FAILED";

export const REQUEST_ORDERS = "REQUEST_ORDERS";
export const REQUEST_ORDERS_SUCCESS = "REQUEST_ORDERS_SUCCESS";
export const REQUEST_ORDERS_FAILED = "REQUEST_ORDERS_FAILED";

export const ATTEND_ORDER = "ATTEND_ORDER";
export const UPDATE_ORDER_SUCCESS = "ATTEND_ORDER_SUCCESS";
export const UPDATE_ORDER_FAILED = "ATTEND_ORDER_FAILED";
export const SEND_NOTIFICATION_TOKEN = "SEND_NOTIFICATION_TOKEN";

export const REFRESH_ORDERS = "REFRESH_ORDERS";
export const CLOSE_ORDER = "CLOSE_ORDER";

export const CHANGE_FILTERING_STATE = "CHANGE_FILTERING_STATE";
export const CHANGE_TO_READY_TO_PICK_UP = "CHANGE_TO_READY_TO_PICK_UP";
export const CHANGE_TO_DISPATCHED = "CHANGE_TO_DISPATCHED";
export const CHANGE_TO_READY_TO_DELIEVER = "CHANGE_TO_READY_TO_DELIVER";
export const SUCCESS_ORDER_STATE_CHANGE = "SUCCESS_ORDER_STATE_CHANGE";
export const CHANGE_TO_PICK_UP = "CHANGE_TO_PICK_UP";
export const INVALID_SECRET_CODE = "INVALID_SECRET_CODE";
export const ERROR_ORDER_STATE_CHANGE = "ERROR_ORDER_STATE_CHANGE";

export const LOAD_LAST_CHATTED_USERS = "LOAD_LAST_CHATTED_USERS";
export const LOAD_LAST_CHATTED_USERS_SUCCESS =
  "LOAD_LAST_CHATTED_USERS_SUCCESS";
export const LOAD_LAST_CHATTED_USERS_FAIL = "LOAD_LAST_CHATTED_USERS_FAIL";
export const CHAT_ON_MESSAGE = "CHAT_ON_MESSAGE";
export const CHAT_LOAD_CHAT_HISTORY = "CHAT_LOAD_CHAT_HISTORY";
export const CHAT_CLEAR_LAST_CHATTED_AND_SELECTED_USER_ON_CHAT_SCREEN =
  "CHAT_CLEAR_LAST_CHATTED_AND_SELECTED_USER_ON_CHAT_SCREEN";
export const CHAT_CLEAR_CHAT = "CHAT_CLEAR_CHAT";
export const CHAT_SELECT_USER_ON_CHAT_SCREEN =
  "CHAT_SELECT_USER_ON_CHAT_SCREEN";
export const CHAT_LOAD_CHAT_HISTORY_SUCCESS = "CHAT_LOAD_CHAT_HISTORY_SUCCESS";
export const CHAT_LOAD_CHAT_HISTORY_FAILED = "CHAT_LOAD_CHAT_HISTORY_FAILED";
export const CHAT_SEND_MESSAGE = "CHAT_SEND_MESSAGE";
export const CHAT_SEND_MESSAGE_SUCCESS = "CHAT_SEND_MESSAGE_SUCCESS";
export const CHAT_SEND_MESSAGE_FAILED = "CHAT_SEND_MESSAGE_FAILED";
export const SUBMIT_ALERT = "SUBMIT_ALERT";
