export const _PUSH_NOTIFICATIONS_REGISTER_USER =
  "_PUSH_NOTIFICATIONS_REGISTER_USER";
export const _PUSH_NOTIFICATIONS_REGISTER_USER_FAILED =
  "_PUSH_NOTIFICATIONS_REGISTER_USER_FAILED";
export const _PUSH_NOTIFICATIONS_REGISTER_USER_SUCCESS =
  "_PUSH_NOTIFICATIONS_REGISTER_USER_SUCCESS";
export const _PUSH_NOTIFICATIONS_UNREGISTER_USER =
  "_PUSH_NOTIFICATIONS_UNREGISTER_USER";
