// chat
export const CHAT_MESSAGE = 'CHAT_MESSAGE';
// orders
export const ORDER_PLACED = 'ORDER_PLACED';
export const ORDER_PAID = 'ORDER_PAID';
export const ORDER_ATTENDED = 'ORDER_ATTENDED';
export const ORDER_CANCELLATION_ACCEPTED = 'ORDER_CANCELLATION_ACCEPTED';
export const ORDER_CANCELLATION_REJECTED = 'ORDER_CANCELLATION_REJECTED';
export const ORDER_CANCELLED = 'ORDER_CANCELLED';
export const ORDER_CLOSED = 'ORDER_CLOSED';
export const ORDER_COMPLETED = 'ORDER_COMPLETED';
export const ORDER_DISPATCHED = 'ORDER_DISPATCHED';
export const ORDER_REFUNDED_AND_CANCELLED = 'ORDER_REFUNDED_AND_CANCELLED';
export const ORDER_REFUNDED_AND_CLOSED = 'ORDER_REFUNDED_AND_CLOSED';
export const DISPUTED_ORDER_REFUNDED = 'DISPUTED_ORDER_REFUNDED';
export const ORDER_READY_TO_DELIVER = 'ORDER_READY_TO_DELIVER';
export const ORDER_READY_TO_PICK_UP = 'ORDER_READY_TO_PICK_UP';
export const ORDER_UNPAID = 'ORDER_UNPAID';
export const ASSIGNED_AS_PICK_UP_PERSON = 'ASSIGNED_AS_PICK_UP_PERSON';
export const REMOVED_AS_PICK_UP_PERSON = 'REMOVED_AS_PICK_UP_PERSON';
export const PICK_UP_PERSON_ACCEPTED = 'PICK_UP_PERSON_ACCEPTED';
export const PICK_UP_PERSON_REJECTED = 'PICK_UP_PERSON_REJECTED';